version: 2
updates:
  - package-ecosystem: docker
    directory: /
    ignore:
      - dependency-name: node
        versions:
          - 14.4.0-alpine3.12
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
